#!/usr/bin/env bash
set -euo pipefail

# Build flat (concatenated) versions of filter lists
# Run from repo root: bash scripts/build.sh

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

build_flat() {
  local dir="$1"
  local header_title="$2"
  local output="$dir/all-flat.txt"

  # Collect all .txt files except all.txt and all-flat.txt, sorted
  local files=()
  for f in "$dir"/*.txt; do
    local base
    base=$(basename "$f")
    if [[ "$base" != "all.txt" && "$base" != "all-flat.txt" ]]; then
      files+=("$f")
    fi
  done

  # Write header
  cat > "$output" <<EOF
! Title: My Custom Filters ($header_title) [COMBINED]
! Description: Auto-generated combined filter list — do not edit manually
! Homepage: https://github.com/YOUR_USERNAME/my-adblock-filters
! Expires: 1 day
! Last modified: $TIMESTAMP
!
! This file is auto-generated by scripts/build.sh
! Edit the individual site files instead.

EOF

  # Concatenate each file with a separator
  for f in "${files[@]}"; do
    local base
    base=$(basename "$f")
    echo "! ======================================================" >> "$output"
    echo "! Source: $base" >> "$output"
    echo "! ======================================================" >> "$output"
    echo "" >> "$output"
    cat "$f" >> "$output"
    echo "" >> "$output"
    echo "" >> "$output"
  done

  echo "Built: $output ($(wc -l < "$output") lines)"
}

# Also update the "Last modified" in barrel files
update_barrel_timestamp() {
  local file="$1"
  if [[ -f "$file" ]]; then
    sed -i "s/^! Last modified:.*/! Last modified: $TIMESTAMP/" "$file"
  fi
}

# Build both platforms
build_flat "ublock" "uBlock Origin"
build_flat "adguard" "AdGuard"

# Update barrel file timestamps
update_barrel_timestamp "ublock/all.txt"
update_barrel_timestamp "adguard/all.txt"

echo "Done."
